### ISSUE TITLE
Test loss in "Final Extremes"

### ISSUE THREAD

**Issue by haoyangz** [Mri-monitoring/Mri-app#12]
In some cases for example [siamese convolutional network](http://yann.lecun.com/exdb/publis/pdf/chopra-05.pdf), the accuracy is not easily defined and we can only evaluate the performance of a hyper-param set by the **testing** loss. In current version, it seems that only **training** loss and testing accuracy are calculated in the "Final Extremes". I wonder if it is possible that the **testing** loss can also be included? Much appreciated!

**Comment by nharada1** [comment]
This actually highlights a more fundamental problem in Mri, namely that the system is not aware of the testing loss at any point. I will implement this soon.

**Comment by nharada1** [comment]
I have fixed this in the latest commit. Mri now also outputs "test_loss" in addition to loss and accuracy.
