### ISSUE TITLE
ValueError: Invalid dispatch found in config file

### ISSUE THREAD

**Issue by cbelth** [Mri-monitoring/Mri-app#14]
I have 'dispatch = mri-server-dispatch' in my config file, but when I run MriApp.py, I get the error:
`ValueError: Invalid dispatch found in config file`

**Comment by nharada1** [comment]
could you attach your config file? did you resolve the dependency issues you had earlier?

**Comment by cbelth** [comment]
`; ---=== Dispatch Settings ===---
; Dispatches events to be plotted locally in Matplotlib
[matplotlib-dispatch]
save_img_folder = /path/to/caffe/monitor      ; Location to save matplotlib outputs
show_windows = False                                    ; Optional, set to True to show plots during training

; Dispatches events to an mri-server
[mri-server-dispatch]
url = https://tigerpanda.herokuapp.com/                 ; Url of server
username = (removed for privacy)                                       ; Username on server
password = (removed for privacy)                              ; Password on server

; ---=== Retrieve Settings ===---
; Retrieve events from a local folder
[local-retrieve]
task_list = /path/to/Mri-app/mriapp/tasks/list.txt          ; Local list of tasks, simply a list of folders containing tasks

; ---=== Client Settings ===---
[mri-client]
log_location = ../mri.log                               ; Log save location
log_level = DEBUG                                       ; "DEBUG", "INFO" or "NONE". Level of verbose logging and stdout (decreasing order)
caffe_root = path/to/caffe               ; Root caffe directory. Caffe must be built!
caffe_bin = ./build/tools/caffe                         ; Path to caffe binary from root caffe folder
solver_type = Caffe                                     ; Currently only Caffe is possible

; Dispatch and Retrieve modules to use
dispatch = mri-server-dispatch                          ; Choose which dispatcher, eg 'mri-server-dispatch' or 'matplotlib-dispatch'
retrieve = local-retrieve                               ; Run with the local retriever`

**Comment by cbelth** [comment]
@nharada1

**Comment by nharada1** [comment]
this is a really strange error to get -- it's coming from https://github.com/Mri-monitoring/Mri-app/blob/0311caa8bec776fd78fd6860de2bdb26e32b1754/mriapp/utilities/verify_config.py and all it's doing is checking if the dispatch setting is that exact text. I don't see why you'd get this error if your config file is the one you attached. Maybe there was some update to a dependency that's causing unexpected behavior changes (unicode or something?). 

Please double check that you are using the correct config file. Maybe try setting dispatch to 'matplotlib-dispatch' just to see if it works. Or at least gives you a different error.

I will get to this eventually, but I no longer have access to the original build environment which means I'll need to reprovision a VM to get the integration tests running. Not a problem, but will maybe take a few days.

**Comment by nharada1** [comment]
Hi @cbelth 

I was unable to recreate this error in my tests. I use [this repo](https://github.com/Mri-monitoring/Mri-integration-testing) for integration testing, and if you have vagrant installed on your machine you should be able to run the tests yourself too. The test runs [this script](https://github.com/Mri-monitoring/Mri-integration-testing/blob/master/run.sh) and calls the various configs, including [this config ](https://github.com/Mri-monitoring/Mri-integration-testing/blob/master/mri-server-config)that is setup for the mri-server. Take a look at those files and make sure that this all looks familiar to you. 

What command are you running to when you run the app?
