### ISSUE TITLE
Different config files for generating tasks

### ISSUE THREAD

**Issue by tf79** [Mri-monitoring/Mri-app#7]
Nothing really important. I have different net architectures. For each I generate tasks but they shouldn't be placed in the same folder and use different hyperparamter files. This requires changing the config file for the generate_tasks script. 

An option to specify the config file would speed things up a little and automatically create the folder to store everything if it hasn't been created, yet. Maybe in the same way the MriApp script allows to use different config files.

**Comment by nharada1** [comment]
Agreed, there is no reason to not implement this. 

Implemented in commit [2bf0fb7622b1127623c6380af545ed4d2f25fb69](https://github.com/Mri-monitoring/Mri-app/commit/2bf0fb7622b1127623c6380af545ed4d2f25fb69)
