### ISSUE TITLE
Constrains for generating tasks

### ISSUE THREAD

**Issue by tf79** [Mri-monitoring/Mri-app#8]
The amount of training tasks grows very quickly with the amount of hyperparameters. However, I think it's possible to reduce the size by specifying conditions between hyperparameters. 

For example: 
param_1: 32, 64
param_2: 32, 64
param_3: 32, 64, 128

number of parameters: 12

condition: param_1 <= param_2 & param_1 <= param_3 & param_2 <= param_3 
number of parameters: 7 (If I'm not mistaken) 

Could be tricky to implement but would be a nice.

**Comment by nharada1** [comment]
Have you tried random search? Bergstra and Bengio showed that randomly selecting hyperparameters can generally find near-optimal hyperparams:

http://www.jmlr.org/papers/volume13/bergstra12a/bergstra12a.pdf

**Comment by tf79** [comment]
Haven't used enough parameter in the first place for random search. Got way better results now. Thanks! 

Still some kind of early stopping criterion would be nice, as mentioned on the other thread.
